markdown: kramdown

kramdown:
  input: GFM

# Setup
title:            Route Rater Blog
tagline:          
url:     

# Serving
baseurl:          /routerater
exclude:          [Gemfile, Gemfile.lock, README.md]

# Outputting
paginate:         5
paginate_path:    "/blog/page:num/"

# Permalinks
permalink:        /blog/:title.html
relative_permalinks: true

# Author
author:
  name:           Mike Davies
  url:            https://twitter.com/peakingatnormal
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/slowe/routerater